name: integration test all
on: pull_request
jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            go:
              - '.github/workflows/**/*.yml'
              - '**/*.go'
              - '**/*.gotpl'
              - '**/*.mod'
              - '**/*.sum'
              - '**/*.work'

      # fix for GitHub actions MacOS
      - name: Setup docker
        if: runner.os == 'macos' && steps.changes.outputs.go == 'true'
        run: |
          brew install docker
          colima start

          # For testcontainers to find the Colima socket
          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache
          restore-keys: ${{ runner.os }}-go-
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: test
        if: steps.changes.outputs.go == 'true'
        run: docker build . --build-arg IMAGE="golang:1" -f test/integration/integration.dockerfile -t integration && docker run integration

  integration-alpine:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            go:
              - '.github/workflows/**/*.yml'
              - '**/*.go'
              - '**/*.gotpl'
              - '**/*.mod'
              - '**/*.sum'
              - '**/*.work'

      # fix for GitHub actions MacOS
      - name: Setup docker
        if: runner.os == 'macos' && steps.changes.outputs.go == 'true'
        run: |
          brew install docker
          colima start

          # For testcontainers to find the Colima socket
          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache
          restore-keys: ${{ runner.os }}-go-
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: test on alpine
        if: steps.changes.outputs.go == 'true'
        run: docker build . --build-arg IMAGE="golang:1-alpine" -f test/integration/integration.dockerfile -t integration && docker run integration
