name: test all
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            go:
              - '.github/workflows/**/*.yml'
              - '**/*.go'
              - '**/*.gotpl'
              - '**/*.mod'
              - '**/*.sum'
              - '**/*.work'

      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache
          restore-keys: ${{ runner.os }}-go-
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: deps
        if: steps.changes.outputs.go == 'true'
        run: go mod download

      - name: setup & generate
        if: steps.changes.outputs.go == 'true'
        run: go generate -tags setup ./...

      - name: test
        if: steps.changes.outputs.go == 'true'
        run: go test ./... -v -failfast
